version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: weather_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: "senha_usuario#01"
    ports:
      - "5306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build: .
    container_name: node_api_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: usuario
      DB_PASSWORD: "senha_usuario#01"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: weather_db
      OPENWEATHER_API_KEY: SUA_CHAVE_AQUI
    ports:
      - "5000:3000"
    volumes:
      - .:/api
      - /api/node_modules
    command: ["npm", "start"]

volumes:
  mysql_data:
