version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: clima_tempo
      MYSQL_USER: usuario
      MYSQL_PASSWORD: "senha"
    ports:
      - "5306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build: .
    container_name: node_api_container
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: usuario
      DB_PASSWORD: "senha"
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: clima_tempo
      OPENWEATHER_API_KEY: 1364e78d9bbbd755755d5843db8cb3d8
      SECRET_KEY: 8e6f6f815b50f474cf0dc22d4f400725
    ports:
      - "3321:3321"
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

volumes:
  mysql_data:
